# Build Agentus Network Windows artifacts: freeze, NSIS setup, portable zip.
# Version is read from backend/pyproject.toml unless -Version is passed.
[CmdletBinding()]
param(
    [string]$Version,
    [switch]$SkipFrontend,
    [switch]$SkipNsis
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$RepoRoot = Split-Path -Parent $PSScriptRoot
$Backend = Join-Path $RepoRoot "backend"
$Frontend = Join-Path $RepoRoot "frontend"
$Installer = Join-Path $RepoRoot "installer"
$Packaging = Join-Path $RepoRoot "packaging"
$Dist = Join-Path $RepoRoot "dist"
$Vendor = Join-Path $Installer "vendor"
$LockPath = Join-Path $Installer "vendor.lock.json"
$FetchUrl = Join-Path $Installer "fetch-url.ps1"
$Spec = Join-Path $Packaging "agentus_network.spec"
$Nsi = Join-Path $Installer "Agentus-Network.nsi"
$Toml = Join-Path $Backend "pyproject.toml"

function Read-ProjectVersion {
    $text = Get-Content -LiteralPath $Toml -Raw -Encoding UTF8
    $match = [regex]::Match($text, '(?m)^version\s*=\s*"([^"]+)"')
    if (-not $match.Success) {
        throw "version not found in $Toml"
    }
    return $match.Groups[1].Value
}

function Get-VersionQuad([string]$ver) {
    $parts = @($ver.Split("."))
    while ($parts.Count -lt 4) {
        $parts += "0"
    }
    return ($parts[0..3] -join ".")
}

function Get-PythonExe {
    $venv = Join-Path $Backend ".venv\Scripts\python.exe"
    if (Test-Path -LiteralPath $venv) {
        return $venv
    }
    $cmd = Get-Command py -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }
    $cmd = Get-Command python -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }
    throw "Python 3.12 not found. Create backend\.venv or install Python."
}

function Invoke-Python {
    param([Parameter(Mandatory = $true)][string[]]$PyArgs)
    $exe = Get-PythonExe
    $prefix = @()
    if ($exe -like "*\py.exe" -or (Split-Path -Leaf $exe) -eq "py.exe") {
        $prefix = @("-3.12")
    }
    & $exe @prefix @PyArgs
    if ($LASTEXITCODE -ne 0) {
        throw "python exited $LASTEXITCODE : $($PyArgs -join ' ')"
    }
}

function Find-Makensis {
    $cmd = Get-Command makensis -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }
    foreach ($candidate in @(
            "${env:ProgramFiles(x86)}\NSIS\makensis.exe",
            "${env:ProgramFiles}\NSIS\makensis.exe",
            "$env:LOCALAPPDATA\Programs\NSIS\makensis.exe",
            (Join-Path $RepoRoot "build\nsis\nsis-3.12\makensis.exe")
        )) {
        if ($candidate -and (Test-Path -LiteralPath $candidate)) {
            return $candidate
        }
    }
    $portable = Get-ChildItem -Path (Join-Path $RepoRoot "build\nsis") -Filter makensis.exe -Recurse -ErrorAction SilentlyContinue |
        Select-Object -First 1 -ExpandProperty FullName
    if ($portable) {
        return $portable
    }
    return $null
}

function Write-GeneratedVersionNsh {
    param([string]$Ver, [string]$Quad, $Lock)
    $wv = $Lock.webview2_bootstrapper
    $ol = $Lock.ollama_setup
    $content = @"
; Generated by scripts/build-windows.ps1 - do not hand-edit
!ifndef PRODUCT_VERSION
  !define PRODUCT_VERSION "$Ver"
!endif
!ifndef PRODUCT_VERSION_QUAD
  !define PRODUCT_VERSION_QUAD "$Quad"
!endif
!define WEBVIEW2_NAME "$($wv.name)"
!define WEBVIEW2_URL "$($wv.url)"
!define WEBVIEW2_SHA256 "$($wv.sha256)"
!define OLLAMA_NAME "$($ol.name)"
!define OLLAMA_URL "$($ol.url)"
!define OLLAMA_SHA256 "$($ol.sha256)"
"@
    $path = Join-Path $Installer "generated-version.nsh"
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($path, $content.TrimStart() + "`n", $utf8)
    Write-Host "wrote $path"
}

function Ensure-VendorFile {
    param($Entry, [string]$DestDir)
    $out = Join-Path $DestDir $Entry.name
    & $FetchUrl -Url $Entry.url -OutFile $out -Sha256 $Entry.sha256
    if ($LASTEXITCODE -ne 0) {
        throw "vendor fetch failed for $($Entry.name)"
    }
}

function Test-FreezeSmoke {
    $exe = Join-Path $Dist "AgentusNetwork\AgentusNetwork.exe"
    if (-not (Test-Path -LiteralPath $exe)) {
        throw "freeze missing $exe"
    }
    $indexCandidates = @(
        (Join-Path $Dist "AgentusNetwork\_internal\frontend\dist\index.html"),
        (Join-Path $Dist "AgentusNetwork\frontend\dist\index.html")
    )
    $index = $indexCandidates | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
    if (-not $index) {
        throw "freeze missing frontend/dist/index.html under onedir"
    }
    $help = @(
        (Join-Path $Dist "AgentusNetwork\_internal\help_docs\de\00-user-guide.md"),
        (Join-Path $Dist "AgentusNetwork\help_docs\de\00-user-guide.md")
    ) | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
    if (-not $help) {
        throw "freeze missing help_docs"
    }
    Write-Host "freeze smoke ok: $exe"
    Write-Host "spa: $index"
}

function New-PortableZip {
    param([string]$Ver)
    $onedir = Join-Path $Dist "AgentusNetwork"
    $stageRoot = Join-Path $Dist "portable"
    $stage = Join-Path $stageRoot "AgentusNetwork"
    if (Test-Path -LiteralPath $stageRoot) {
        Remove-Item -LiteralPath $stageRoot -Recurse -Force
    }
    New-Item -ItemType Directory -Path $stage | Out-Null
    Copy-Item -Path (Join-Path $onedir "*") -Destination $stage -Recurse -Force
    $marker = Join-Path $stage "portable.txt"
    Set-Content -LiteralPath $marker -Value "portable`n" -Encoding ascii
    if (Test-Path -LiteralPath (Join-Path $onedir "portable.txt")) {
        throw "portable.txt must not live in the NSIS onedir payload"
    }
    $zip = Join-Path $Dist "Agentus-Network-Portable-$Ver-x64.zip"
    if (Test-Path -LiteralPath $zip) {
        Remove-Item -LiteralPath $zip -Force
    }
    $tar = Get-Command tar.exe -ErrorAction SilentlyContinue
    if ($tar) {
        Push-Location $stageRoot
        try {
            & $tar.Source -a -c -f $zip "AgentusNetwork"
            if ($LASTEXITCODE -ne 0) {
                throw "tar exited $LASTEXITCODE creating $zip"
            }
        }
        finally {
            Pop-Location
        }
    }
    else {
        Compress-Archive -Path $stage -DestinationPath $zip -Force
    }
    Write-Host "portable zip: $zip"
}

function Invoke-SignIfConfigured {
    param([string[]]$Files)
    $cert = $env:AGENTUS_NETWORK_SIGN_CERT
    if (-not $cert) {
        Write-Warning "No AGENTUS_NETWORK_SIGN_CERT; skipping signtool (v1)."
        return
    }
    $signtool = Get-Command signtool -ErrorAction SilentlyContinue
    if (-not $signtool) {
        Write-Warning "signtool not on PATH; skipping signing."
        return
    }
    foreach ($file in $Files) {
        if (-not (Test-Path -LiteralPath $file)) { continue }
        & $signtool.Source sign /fd SHA256 /a /f $cert $file
        if ($LASTEXITCODE -ne 0) {
            throw "signtool failed for $file"
        }
    }
}

if (-not $Version) {
    $Version = Read-ProjectVersion
}
$VersionQuad = Get-VersionQuad $Version
Write-Host "version $Version ($VersionQuad)"

if (-not (Test-Path -LiteralPath $LockPath)) {
    throw "missing $LockPath"
}
$Lock = Get-Content -LiteralPath $LockPath -Raw -Encoding UTF8 | ConvertFrom-Json
foreach ($key in @("webview2_bootstrapper", "ollama_setup")) {
    $entry = $Lock.$key
    if (-not $entry -or -not $entry.name -or -not $entry.url -or -not $entry.sha256) {
        throw "vendor.lock.json missing $key name/url/sha256"
    }
}

Write-GeneratedVersionNsh -Ver $Version -Quad $VersionQuad -Lock $Lock

if (-not $SkipFrontend) {
    Push-Location $Frontend
    try {
        if (-not (Test-Path -LiteralPath (Join-Path $Frontend "node_modules"))) {
            Write-Host "npm ci"
            npm ci
            if ($LASTEXITCODE -ne 0) { throw "npm ci failed" }
        }
        Write-Host "npm run build"
        npm run build
        if ($LASTEXITCODE -ne 0) { throw "npm run build failed" }
    }
    finally {
        Pop-Location
    }
}

$indexHtml = Join-Path $Frontend "dist\index.html"
if (-not (Test-Path -LiteralPath $indexHtml)) {
    throw "frontend/dist/index.html missing; run without -SkipFrontend"
}

Write-Host "pip install -e .[packaging]"
Push-Location $Backend
try {
    Invoke-Python -PyArgs @("-m", "pip", "install", "-e", ".[packaging]")
}
finally {
    Pop-Location
}

if (-not (Test-Path -LiteralPath $Dist)) {
    New-Item -ItemType Directory -Path $Dist | Out-Null
}

Write-Host "pyinstaller $Spec"
$pyiLog = Join-Path $RepoRoot "build\pyinstaller.log"
$pyiErr = Join-Path $RepoRoot "build\pyinstaller.err.log"
if (-not (Test-Path -LiteralPath (Join-Path $RepoRoot "build"))) {
    New-Item -ItemType Directory -Path (Join-Path $RepoRoot "build") | Out-Null
}
$pyExe = Get-PythonExe
$pyPrefix = @()
if ($pyExe -like "*\py.exe" -or (Split-Path -Leaf $pyExe) -eq "py.exe") {
    $pyPrefix = @("-3.12")
}
$pyiArgs = $pyPrefix + @(
    "-m", "PyInstaller", $Spec,
    "--noconfirm", "--clean",
    "--log-level", "WARN",
    "--distpath", $Dist,
    "--workpath", (Join-Path $RepoRoot "build")
)
Push-Location $RepoRoot
try {
    $proc = Start-Process -FilePath $pyExe -ArgumentList $pyiArgs -Wait -PassThru -NoNewWindow `
        -RedirectStandardOutput $pyiLog -RedirectStandardError $pyiErr
    if ($proc.ExitCode -ne 0) {
        Write-Host (Get-Content -LiteralPath $pyiErr -Raw -ErrorAction SilentlyContinue)
        Write-Host (Get-Content -LiteralPath $pyiLog -Tail 40 -ErrorAction SilentlyContinue)
        throw "pyinstaller exited $($proc.ExitCode); see $pyiLog"
    }
}
finally {
    Pop-Location
}

Test-FreezeSmoke
New-PortableZip -Ver $Version

$setup = Join-Path $Dist "Agentus-Network-Setup-$Version-x64.exe"
$exe = Join-Path $Dist "AgentusNetwork\AgentusNetwork.exe"

if (-not $SkipNsis) {
    if (-not (Test-Path -LiteralPath $Vendor)) {
        New-Item -ItemType Directory -Path $Vendor | Out-Null
    }
    Ensure-VendorFile -Entry $Lock.webview2_bootstrapper -DestDir $Vendor
    $makensis = Find-Makensis
    if (-not $makensis) {
        throw "makensis not found. Install NSIS 3 Unicode and re-run, or pass -SkipNsis."
    }
    Write-Host "makensis $makensis"
    & $makensis "/DPRODUCT_VERSION=$Version" "/DPRODUCT_VERSION_QUAD=$VersionQuad" $Nsi
    if ($LASTEXITCODE -ne 0) {
        throw "makensis exited $LASTEXITCODE"
    }
    if (-not (Test-Path -LiteralPath $setup)) {
        throw "setup exe missing $setup"
    }
    $minBytes = 8MB
    $size = (Get-Item -LiteralPath $setup).Length
    if ($size -lt $minBytes) {
        throw "setup exe too small ($size bytes); payload missing?"
    }
    Write-Host "setup: $setup ($size bytes)"
}

$signFiles = @($exe)
if (Test-Path -LiteralPath $setup) { $signFiles += $setup }
Invoke-SignIfConfigured -Files $signFiles

Write-Host "done version=$Version"
Write-Host "freeze $exe"
Write-Host "portable $(Join-Path $Dist "Agentus-Network-Portable-$Version-x64.zip")"
if (Test-Path -LiteralPath $setup) {
    Write-Host "setup $setup"
}
