; Generated by scripts/build-windows.ps1 - do not hand-edit
!ifndef PRODUCT_VERSION
  !define PRODUCT_VERSION "0.1.0"
!endif
!ifndef PRODUCT_VERSION_QUAD
  !define PRODUCT_VERSION_QUAD "0.1.0.0"
!endif
!define WEBVIEW2_NAME "MicrosoftEdgeWebview2Setup.exe"
!define WEBVIEW2_URL "https://go.microsoft.com/fwlink/p/?LinkId=2124703"
!define WEBVIEW2_SHA256 "81c01751c8cc385a5991abb104205d42ac70094350ee8fb9e8ea580b51bb9554"
!define OLLAMA_NAME "OllamaSetup.exe"
!define OLLAMA_URL "https://github.com/ollama/ollama/releases/download/v0.34.4/OllamaSetup.exe"
!define OLLAMA_SHA256 "4a6514323eb8c131f6c8bb651b4fe2edf5f1525f4fd8b84315ba20f1af3e210f"
