; Generated by scripts/build-windows.ps1 - do not hand-edit
!ifndef PRODUCT_VERSION
  !define PRODUCT_VERSION "0.1.0"
!endif
!ifndef PRODUCT_VERSION_QUAD
  !define PRODUCT_VERSION_QUAD "0.1.0.0"
!endif
!define WEBVIEW2_NAME "MicrosoftEdgeWebview2Setup.exe"
!define WEBVIEW2_URL "https://go.microsoft.com/fwlink/p/?LinkId=2124703"
!define WEBVIEW2_SHA256 "83004a28553bcf2f932bf03564fbab407b8e1f59cd265f8dc99cc53d028e459c"
!define OLLAMA_NAME "OllamaSetup.exe"
!define OLLAMA_URL "https://github.com/ollama/ollama/releases/download/v0.34.2/OllamaSetup.exe"
!define OLLAMA_SHA256 "8c9eb7ba71f3c6a62df4c7d204cc4739d90c335e1cbeb07c99fd471544066a8b"
